CREATE TABLE MARCA (
	NOMBRE		VARCHAR(30)	NOT NULL
);

CREATE TABLE MODELO (
NOMBRE_MODELO	VARCHAR(30) NOT NULL,
NOMBRE_MARCA	VARCHAR(30) NOT NULL
);


CREATE TABLE PRODUCTO (
CODIGO				NUMERIC(21,0) 	NOT NULL,
NOMBRE_PRODUCTO		VARCHAR(30) 	NOT NULL,
DESCRIPCION			TEXT 			NOT NULL,
NOMBRE_MARCA		VARCHAR(30)		NOT NULL,
NOMBRE_MODELO		VARCHAR(30)		NOT NULL
);

CREATE TABLE LISTA_PRECIOS(
CODIGO_P			NUMERIC(21,0)  	NOT NULL,
AÑO_ELAB			NUMERIC(4,0)	NOT NULL,
PRECIO 				NUMERIC(21,0)	NOT NULL
);

CREATE TABLE PROVEEDORA(
RIF					VARCHAR(20)		NOT NULL,
NOMBRE 				VARCHAR(30)		NOT NULL,
DIRECCION 			TEXT			NOT NULL
);

CREATE TABLE TELEFONO_PRO(
RIF_P 				VARCHAR(20)		NOT NULL,
TELEFONO 			NUMERIC(11,0)	NOT NULL
);

CREATE TABLE ORDEN(
NUMERO				NUMERIC(11,0)	NOT NULL,
FECHA				DATE			NOT NULL,
MONTO				NUMERIC(21,0)	NOT NULL,
RIF_P				VARCHAR(20)		NOT NULL
);

CREATE TABLE SE_PIDE(
CODIGO_P			NUMERIC(21,0)	NOT NULL,
NUM_ORDEN			NUMERIC(21,0)	NOT NULL,
CANTIDAD			NUMERIC(15,0)	NOT NULL
);

CREATE TABLE LOTE(
SERIAL_F 			NUMERIC(21,0)	NOT NULL,
NUM_ORDEN			NUMERIC(21,0)	NOT NULL,
RIF_P				VARCHAR(20)		NOT NULL,
FECHA 				DATE			NOT NULL,
MONTO				NUMERIC(21,0)	NOT NULL
);

CREATE TABLE SE_PAGA(
SERIAL_F 			NUMERIC(21,0) 	NOT NULL,
FECHA 				DATE			NOT NULL,
MONTO 				NUMERIC(21,0)	NOT NULL,
NUM_TRANSACCION		NUMERIC(21,0)	NOT NULL,
NUM_CUENTA			NUMERIC(21,0)	NOT NULL
);


CREATE TABLE ARTICULO_N(
NUM_INV 			NUMERIC(9,0)	NOT NULL,
ULT_COSTO			NUMERIC(21,0) 	NOT NULL,
MINIMO				NUMERIC(9,0) 	NOT NULL,
CATEGORIA			TEXT			NOT NULL,
AÑO_ELAB			NUMERIC(4,0)	NOT NULL,
PRECIO_VENTA		NUMERIC(21,0)	NOT NULL,
COD_PRODUCTO		NUMERIC(21,0)	NOT NULL
);

CREATE TABLE ARTICULO_U(
NUM_INV				NUMERIC(9,0)	NOT NULL,
CATEGORIA			TEXT 			NOT NULL,
AÑO_ELAB			NUMERIC(4,0) 	NOT NULL,
COD_PRODUCTO		NUMERIC(21,0) 	NOT NULL
);

CREATE TABLE CONTIENE(
FACT_LOTE			NUMERIC(21,0)	NOT NULL,
NUM_INV 			NUMERIC(9,0)	NOT NULL,
CANTIDAD			NUMERIC(9,0)	NOT NULL
);

CREATE TABLE PRIMA(
SEXO				CHAR			NOT NULL,		
GRUPO_ET			VARCHAR(10)		NOT NULL, 
MONTO				NUMERIC(9,0)	NOT NULL
);

CREATE TABLE DEPENDIENTE(
NUM_DEP				NUMERIC(5,0) 	NOT NULL,
NOMBRE 				VARCHAR(30)		NOT NULL,
APELLIDO			VARCHAR(30)		NOT NULL,
SEXO 				CHAR			NOT NULL,		
EDAD				NUMERIC(2,0)	NOT NULL,
DIRECCION			TEXT			NOT NULL,
CORREO				VARCHAR(50)		NOT NULL,
SEXO_P				CHAR			NOT NULL
);

CREATE TABLE PERSONA(
CEDULA				NUMERIC(9,0)	NOT NULL,
NOMBRE 				VARCHAR(30)		NOT NULL,
APELLIDO			VARCHAR(30)		NOT NULL,
SEXO 				CHAR			NOT NULL,
EDAD				NUMERIC(2,0)	NOT NULL,
DIRECCION			TEXT			NOT NULL,
CORREO				VARCHAR(50)		NOT NULL
);

CREATE TABLE TELEFONO_P(
CEDULA 				NUMERIC(9,0)	NOT NULL,
NUMERO				NUMERIC(11,0)			NOT NULL
);

CREATE TABLE EMPLEADO(
CEDULA				NUMERIC(9,0)	NOT NULL,
FECHA_INGRESO		DATE			NOT NULL,
SUELDO_BASE			NUMERIC(21,0)	NOT NULL
);

CREATE TABLE PARIENTE(
NUM_DEP				NUMERIC(9,0)	NOT NULL,
CEDULA				NUMERIC(9,0)	NOT NULL,
PARENTEZCO			VARCHAR(25) 	NOT NULL
);

CREATE TABLE VENDEDOR(
CEDULA				NUMERIC(9,0)	NOT NULL,
CATEGORIA			VARCHAR(3)		NOT NULL,
SUELDO 				NUMERIC(15,0)	NOT NULL,
TURNO				VARCHAR(10)		NOT NULL,
NUM_SABADOS			NUMERIC(1,0) 	NOT NULL
);


CREATE TABLE ADMINISTRATIVO(
CEDULA				NUMERIC(9,0)	NOT NULL,
CARGO				VARCHAR(20)		NOT NULL
);

CREATE TABLE CLIENTE(
CEDULA				NUMERIC(9,0)	NOT NULL
);

CREATE TABLE PEDIDO(
NUM_PEDIDO			NUMERIC(21,0)	NOT NULL
);

CREATE TABLE SE_SOLICITA(
NUM_PEDIDO			NUMERIC(21,0)	NOT NULL,
CODIGO_P			NUMERIC(21,0)	NOT NULL,
CANTIDAD			NUMERIC(21,0)	NOT NULL
);

CREATE TABLE TRUEQUE(
SERIAL_R 			NUMERIC(21,0) 	NOT NULL,
FECHA 				DATE			NOT NULL,
MONTO				NUMERIC(21,0)	NOT NULL,
FORMA_PAGO			VARCHAR(20)		NOT NULL,
NUM_TARJETA			NUMERIC(21,0),		
CLAVE_CONF			NUMERIC(21,0)	
);

CREATE TABLE CAMBIO(
NUM_INV_C			NUMERIC(21,0)	NOT NULL,
SERIAL_TRUQUE		NUMERIC(21,0)	NOT NULL,
NUM_INV_T			NUMERIC(21,0)	NOT NULL
);

CREATE TABLE VENTA(
SERIAL_F			NUMERIC(21,0)	NOT NULL,
FECHA 				DATE			NOT NULL,
MONTO 				NUMERIC(21,0)	NOT NULL,
FORMA_PAGO 			VARCHAR(20)		NOT NULL,
NUM_TARJETA			NUMERIC(21,0),
CLAVE_CONF			NUMERIC(21,0)	
);

CREATE TABLE VENTA_N(
SERIAL_V 			NUMERIC(21,0)	NOT NULL,
NUM_INV 			NUMERIC(21,0)	NOT NULL,
CANTIDAD			NUMERIC(15,0)	NOT NULL
);

CREATE TABLE VENTA_U(
SERIAL_V 			NUMERIC(21,0)	NOT NULL,
NUM_INV 			NUMERIC(21,0)	NOT NULL,
CANTIDAD			NUMERIC(15,0)	NOT NULL
);

CREATE TABLE REALIZA_VENTA(
SERIAL_F			NUMERIC(21,0)	NOT NULL,
CEDULA_CLIENTE		NUMERIC(9,0)	NOT NULL,
CEDULA_VENDEDOR		NUMERIC(9,0)	NOT NULL
);

CREATE TABLE REALIZA_PEDIDO(
NUM_PEDIDO			NUMERIC(21,0)	NOT NULL,
CEDULA_CLIENTE		NUMERIC(9,0)	NOT NULL,
CEDULA_VENDEDOR		NUMERIC(9,0)	NOT NULL
);

CREATE TABLE REALIZA_TRUEQUE(
SERIAL_R			NUMERIC(21,0)	NOT NULL,
CEDULA_CLIENTE		NUMERIC(9,0)	NOT NULL,
CEDULA_VENDEDOR		NUMERIC(9,0)	NOT NULL
);