ALTER TABLE MARCA
	ADD CONSTRAINT PK_MARCA PRIMARY KEY (NOMBRE);

ALTER TABLE MODELO
	ADD CONSTRAINT PK_MODELO PRIMARY KEY (NOMBRE_MARCA,NOMBRE_MODELO);
ALTER TABLE MODELO 
	ADD CONSTRAINT FK_MODELO FOREIGN KEY (NOMBRE_MARCA) REFERENCES MARCA;

ALTER TABLE PRODUCTO
	ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO);
ALTER TABLE PRODUCTO
	ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (NOMBRE_MARCA,NOMBRE_MODELO) REFERENCES MODELO;
ALTER TABLE PRODUCTO
	ADD CONSTRAINT NO_NEGATIVIDAD_CODIGO_PRODUCTO CHECK(CODIGO>0);

ALTER TABLE LISTA_PRECIOS
	ADD CONSTRAINT PK_LISTA_PRECIOS PRIMARY KEY (CODIGO_P,AÑO_ELAB);
ALTER TABLE LISTA_PRECIOS
	ADD CONSTRAINT FK_LISTA_PRECIOS FOREIGN KEY (CODIGO_P) REFERENCES PRODUCTO;
ALTER TABLE LISTA_PRECIOS
	ADD CONSTRAINT AÑO_LISTA_PRECIOS CHECK(AÑO_ELAB>1900);
ALTER TABLE LISTA_PRECIOS
	ADD CONSTRAINT NO_NEGATIVIDAD_CODIGO_P_LISTA_PRECIOS CHECK(CODIGO_P>0);
ALTER TABLE LISTA_PRECIOS
	ADD CONSTRAINT NO_NEGTIVIDAD_PRECIO_LISTA_PRECIOS CHECK(PRECIO>0);

ALTER TABLE PROVEEDORA
	ADD CONSTRAINT PK_PROVEEDORA PRIMARY KEY (RIF);

ALTER TABLE TELEFONO_PRO
	ADD CONSTRAINT PK_TELEFONO_PRO PRIMARY KEY (RIF_P, NUMERO);
ALTER TABLE TELEFONO_PRO
	ADD CONSTRAINT FK_TELEFONO_PRO FOREIGN KEY (RIF_P) REFERENCES PROVEEDORA;
ALTER TABLE TELEFONO_PRO
	ADD CONSTRAINT NO_NEGATIVIDAD_TLF_TELEFONO_PRO CHECK(TELEFONO>0);

ALTER TABLE ORDEN
	ADD CONSTRAINT PK_ORDEN PRIMARY KEY (NUM);
ALTER TABLE ORDEN
	ADD CONSTRAINT NO_NEGATIVIDAD_MONTO_ORDEN CHECK(MONTO>0);
ALTER TABLE ORDEN
	ADD CONSTRAINT NO_NEGATIVIDAD_NUMERO_ORDEN CHECK(NUMERO>0);

ALTER TABLE SE_PIDE
	ADD CONSTRAINT PK_SE_PIDE PRIMARY KEY (CODIGO_P,NUM_ORDEN);
ALTER TABLE SE_PIDE
	ADD CONSTRAINT FK_SE_PIDE_PRODCTO FOREIGN KEY (CODIGO_P) REFERENCES PRODUCTO;
ALTER TABLE SE_PIDE
	ADD CONSTRAINT FK_SE_PIDE_ORDEN FOREIGN KEY (NUM_ORDEN) REFERENCES ORDEN;
ALTER TABLE SE_PIDE
	ADD CONSTRAINT NO_NEGATIVIDAD_CODIGO_P_SE_PIDE CHECK(CODIGO_P>0);
ALTER TABLE SE_PIDE
	ADD CONSTRAINT NO_NEGATIVIDAD_NUM_ORDEN_SE_PIDE CHECK(NUM_ORDEN>0);
ALTER TABLE SE_PIDE
	ADD CONSTRAINT NO_NEGATIVIDAD_CANTIDAD_SE_PIDE CHECK(CANTIDAD>0);

ALTER TABLE LOTE
	ADD CONSTRAINT PK_LOTE PRIMARY KEY (SERIAL_F);
ALTER TABLE LOTE
	ADD CONSTRAINT FK_LOTE_ORDEN FOREIGN KEY (NUM_ORDEN) REFERENCES ORDEN;
ALTER TABLE LOTE
	ADD CONSTRAINT FK_LOTE_PROVEEDORA FOREIGN KEY (RIF_P) REFERENCES PROVEEDORA;
ALTER TABLE LOTE
	ADD CONSTRAINT NO_NEGATIVIDAD_SERIAL_F_LOTE CHECK(SERIAL_F>0);
ALTER TABLE LOTE
	ADD CONSTRAINT NO_NEGATIVIDAD_NUM_ORDEN_LOTE CHECK(NUM_ORDEN>0);
ALTER TABLE LOTE
	ADD CONSTRAINT NO_NEGATIVIDAD_MONTO_LOTE CHECK(MONTO>0);

ALTER TABLE SE_PAGA
	ADD CONSTRAINT PK_SE_PAGA PRIMARY KEY (SERIAL_L);
ALTER TABLE SE_PAGA
	ADD CONSTRAINT FK_SE_PAGA PRIMARY KEY (SERIAL_L) REFERENCES LOTE;
ALTER TABLE SE_PAGA
	ADD CONSTRAINT NO_NEGATIVIDAD_SE_PAGA_SERIAL CHECK(SERIAL_F>0);
ALTER TABLE SE_PAGA
	ADD CONSTRAINT NO_NEGATIVIDAD_SE_PAGA_MONTO CHECK(MONTO>0);
ALTER TABLE SE_PAGA
	ADD CONSTRAINT NO_NEGATIVIDAD_SE_PAGA_NUM_TRA CHECK(NUM_TRANSACCION>0);
ALTER TABLE SE_PAGA
	ADD CONSTRAINT NO_NEGATIVIDAD_SE_PAGA_NUM_CUENTA CHECK(NUM_CUENTA>0);

ALTER TABLE ARTICULO_N
	ADD	CONSTRAINT PK_ARTICULO_N PRIMARY KEY (NUM_INV);
ALTER TABLE ARTICULO_N
	ADD CONSTRAINT FK_ARTICULO_N FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO;
ALTER TABLE ARTICULO_N
	ADD CONSTRAINT NO_NEGATIVO_ARTICULO_N_NUM_I CHECK(NUM_INV>0);
ALTER TABLE ARTICULO_N
	ADD CONSTRAINT NO_NEGATIVO_ARTICULO_N_ULT_COSTO CHECK(ULT_COSTO>0);
ALTER TABLE ARTICULO_N
	ADD CONSTRAINT NO_NEGATIVO_ARTICULO_N_MIN CHECK(MINIMO>0);
ALTER TABLE ARTICULO_N
	ADD CONSTRAINT AÑO_ELAB_VALID_ARTICULO_N CHECK(AÑO_ELAB>1900);
ALTER TABLE ARTICULO_N
	ADD CONSTRAINT NO_NEGATIVO_ARTICULO_N_P_VENTA CHECK(PRECIO_VENTA>0);
ALTER TABLE ARTICULO_N
	ADD CONSTRAINT NO_NEGATIVO_ARTICULO_N_COD CHECK(COD_PRODUCTO>0);

ALTER TABLE ARTICULO_U
	ADD CONSTRAINT PK_ARTICULO_U PRIMARY KEY (NUM_INV);
ALTER TABLE ARTICULO_U
	ADD CONSTRAINT FK_ARTICULO_U FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO;
ALTER TABLE ARTICULO_U
	ADD CONSTRAINT NO NO_NEGATIVO_ARTICULO_U_N_INV CHECK(NUM_INV>0);
ALTER TABLE ARTICULO_U
	ADD CONSTRAINT AÑO_ELAB_VALID_ARTICULO_U CHECK(AÑO_ELAB>1900);
ALTER TABLE ARTICULO_U
	ADD CONSTRAINT NO_NEGATIVO_ARTICULO_U_COD CHECK(ARTICULO_U>0);


ALTER TABLE CONTIENE
	ADD CONSTRAINT PK_CONTIENE PRIMARY KEY (FACT_LOTE, NUM_INV);
ALTER TABLE CONTIENE
	ADD CONSTRAINT FK_CONTIENE_LOTE FOREIGN KEY (FACT_LOTE) REFERENCES LOTE;
ALTER TABLE CONTIENE
	ADD CONSTRAINT FK_CONTIENE_ARTICULO_N FOREIGN KEY (NUM_INV) REFERENCES ARTICULO_N;
ALTER TABLE CONTIENE
	ADD CONSTRAINT NO_NEGATIVA_CONTIENE_FACT_L CHECK(FACT_LOTE>0);
ALTER TABLE CONTIENE
	ADD CONSTRAINT NO_NEGATIVO_CONTIENE_N_INV CHECK(NUM_INV>0);
ALTER TABLE CONTIENE
	ADD CONSTRAINT NO_NEGATIVA_CONTIENE_CANT CHECK(CANTIDAD>0);


ALTER TABLE PRIMA 
	ADD CONSTRAINT PK_PRIMA PRIMARY KEY (SEXO, GRUPO_ET);
ALTER TABLE PRIMA
	ADD CONSTRAINT SEXO_VALID_PRIMA CHECK(SEXO IN ('F','M'));
ALTER TABLE PRIMA
	ADD CONSTRAINT GRUPO_ET_VALID_PRIMA CHECK(GRUPO_ET IN ('JOVEN','ADULTO', 'MAYOR', 'MENOR'))
ALTER TABLE PRIMA
	ADD CONSTRAINT NO_NEGATIVO_MONTO_PRIMA CHECK(MONTO>0);


ALTER TABLE DEPENDIENTE
	ADD CONSTRAINT PK_DEPENDIENTE PRIMARY KEY (NUM_DEP);
ALTER TABLE DEPENDIENTE
	ADD	CONSTRAINT FK_DEPENDIENTE FOREIGN KEY (SEXO, GRUPO_ET) REFERENCES PRIMA;
ALTER TABLE DEPENDIENTE
	ADD CONSTRAINT NO_NEGATIVO_DEPENDIENTE_NUM_DEP CHECK(NUM_DEP>0);
ALTER TABLE DEPENDIENTE
	ADD CONSTRAINT SEXO_VALID_DEPENDIENTE CHECK(SEXO IN ('F','M'));
ALTER TABLE DEPENDIENTE
	ADD CONSTRAINT SEXO_P_VALID_DEPENDIENTE CHECK(SECO_P IN ('F','M'));
ALTER TABLE DEPENDIENTE
	ADD CONSTRAINT EDAD_VALID_DEPENDIENTE CHECK(EDAD>0);


ALTER TABLE PERSONA 
	ADD CONSTRAINT PK_PERSONA PRIMARY KEY (CEDULA);
ALTER TABLE PERSONA
	ADD CONSTRAINT CEDULA_VALIDA_PERSONA CHECK(CEDULA>0);
ALTER TABLE PERSONA
	ADD CONSTRAINT SEXO_VALID_PERSONA CHECK(SEXO IN ('F','M'));
ALTER TABLE PERSONA
	ADD CONSTRAINT EDAD_VALID_PERSONA CHECK(EDAD>0);



ALTER TABLE TELEFONO_P
	ADD CONSTRAINT PK_TELEFONO_P PRIMARY KEY (CEDULA,NUMERO);
ALTER TABLE TELEFONO_P
	ADD CONSTRAINT FK_TELEFONO_P FOREIGN KEY (CEDULA) REFERENCES PERSONA;
ALTER TABLE TELEFONO_P
	ADD CONSTRAINT CEDULA_VALIDA_TELF_P CHECK(CEDULA>0);
ALTER TABLE TELEFONO_P
	ADD CONSTRAINT NUM_VALID_TELF_P CHECK(NUMERO>0);


ALTER TABLE EMPLEADO
	ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA);
ALTER TABLE EMPLEADO
	ADD CONSTRAINT FK_EMPLEADO FOREIGN KEY (CEDULA) REFERENCES PERSONA;
ALTER TABLE EMPLEADO
	ADD CONSTRAINT CEDULA_VALID_EMPLEADO CHECK(CEDULA>0);
ALTER TABLE EMPLEADO
	ADD CONSTRAINT SUELDO_VALID_EMPLEADO CHECK(SUELDO_BASE>0);

ALTER TABLE PARIENTE
	ADD CONSTRAINT PK_PARIENTE PRIMARY KEY (NUM_DEP, CEDULA),
ALTER TABLE PARIENTE
	ADD CONSTRAINT FK_PARIENTE_DEPENDIENTE FOREIGN KEY (NUM_DEP) REFERENCES DEPENDIENTE;
ALTER TABLE PARIENTE
	ADD	CONSTRAINT FK_PARIENTE_PERSONA FOREIGN KEY (CEDULA) REFERENCES PERSONA;
ALTER TABLE PARIENTE
 	ADD CONSTRAINT NUM_DEP_VALID_PARIENTE CHECK(NUM_DEP>0);
 ALTER TABLE PARIENTE
 	ADD CONSTRAINT CEDULA_VALID_PARIENTE CHECK(CEDULA>0);

ALTER TABLE VENDEDOR 
	ADD CONSTRAINT PK_VENDEDOR PRIMARY KEY (CEDULA);
ALTER TABLE VENDEDOR
	ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (CEDULA) REFERENCES EMPLEADO;
ALTER TABLE VENDEDOR
	ADD CONSTRAINT VALID_SABADOS_VENDEDOR CHECK(NUM_SABADOS>-1 AND NUM_SABADOS<6);
ALTER TABLE VENDEDOR
	ADD CONSTRAINT CEDULA_VALID_EMPLEADO CHECK(CEDULA>0);
ALTER TABLE VENDEDOR
	ADD CONSTRAINT SUELDO_VALID_VENDEDOR CHECK(SUELDO>0);
ALTER TABLE VENDEDOR
	ADD CONSTRAINT CATEGORIA_VALID_VENDEDOR CHECK(CATEGORIA IN ('I','II','III'));


ALTER TABLE ADMINISTRATIVO 
	ADD CONSTRAINT PK_ADMINISTRATIVO PRIMARY KEY (CEDULA);
ALTER TABLE ADMINISTRATIVO
	ADD CONSTRAINT FK_ADMINISTRATIVO FOREIGN KEY (CEDULA) REFERENCES EMPLEADO; 
ALTER TABLE ADMINISTRATIVO
	ADD CONSTRAINT CEDULA_VALID_ADMINISTRATIVO CHECK(CEDULA>0);


ALTER TABLE CLIENTE
	ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CEDULA);
ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (CEDULA) REFERENCES PERSONA;
ALTER TABLE CLIENTE
	ADD CONSTRAINT CEDULA_VALID_CLIENTE CHECK(CEDULA>0);


ALTER TABLE PEDIDO
	ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUM_PEDIDO);
ALTER TABLE PEDIDO
	ADD CONSTRAINT NUM_PEDIDO_VALID_PEDIDO CHECK(NUM_PEDIDO>0);


ALTER TABLE SE_SOLICITA
	ADD CONSTRAINT PK_SE_SOLICITA PRIMARY KEY (NUM_PEDIDO, CODIGO_P);
ALTER TABLE SE_SOLICITA
	ADD CONSTRAINT NUM_PED_VALID_SE_SOLICITA CHECK(NUM_PEDIDO>0);
ALTER TABLE SE_SOLICITA
	ADD CONSTRAINT COD_P_VALID_SE_SOLICITA CHECK(CODIGO_P>0);
ALTER TABLE SE_SOLICITA
	ADD CONSTRAINT CANTIDAD_VALID_SE_SOLICITA CHECK(CANTIDAD>0);


ALTER TABLE TRUEQUE
	ADD CONSTRAINT PK_TRUEQUE PRIMARY KEY (SERIAL_R);
ALTER TABLE TRUEQUE
	ADD CONSTRAINT SERIAL_R_VALID_TRUEQUE CHECK(SERIAL_R>0);
ALTER TABLE TRUEQUE
	ADD CONSTRAINT NUM_TARJETA_VALID_TRUEQUE CHECK(NUM_TARJETA>0);
ALTER TABLE TRUEQUE
	ADD CONSTRAINT CLAVE_CONF_VALID_TRUQUE CHECK(NUM_TARJETA>0);


ALTER TABLE CAMBIO 
	ADD CONSTRAINT PK_CAMBIO PRIMARY KEY (NUM_INV_C, SERIAL_TRUQUE);
ALTER TABLE CAMBIO
	ADD CONSTRAINT FK_CAMBIO_ARTICULO_U FOREIGN KEY (NUM_INV_C) REFERENCES TRUEQUE;
ALTER TABLE CAMBIO
	ADD CONSTRAINT FK_CAMBIO_TRUEQUE FOREIGN KEY (SERIAL_TRUQUE) REFERENCES TRUEQUE;
ALTER TABLE CAMBIO
	ADD CONSTRAINT NUM_INV_C_VALID_CAMBIO CHECK(NUM_INV_C>0);
ALTER TABLE CAMBIO
	ADD CONSTRAINT SERIAL_T_VALID_CAMBIO CHECK(SERIAL_TRUQUE>0);
ALTER TABLE CAMBIO
	ADD CONSTRAINT NUM_INV_T_VALID_CAMBIO CHECK(NUM_INV_T>0);


ALTER TABLE VENTA
	ADD CONSTRAINT PK_VENTA PRIMARY KEY (SERIAL_F);
ALTER TABLE VENTA
	ADD CONSTRAINT SERIAL_F_VALID_VENTA CHECK(SERIAL_F>0);
ALTER TABLE VENTA
	ADD CONSTRAINT MONTO_CALID_VENTA CHECK(MONTO>0);
ALTER TABLE VENTA
	ADD CONSTRAINT N_TARJETA_VALID_VENTA CHECK(NUM_TARJETA>0);
ALTER TABLE VENTA
	ADD CONSTRAINT CLAVE_CONF_VALID_VENTA CHECK(CLAVE_CONF>0);


ALTER TABLE VENTA_N
	ADD CONSTRAINT PK_VENTA_N PRIMARY KEY (SERIAL_V, NUM_INV);
ALTER TABLE VENTA_N
	ADD CONSTRAINT FK_VENTA_N_VENTA FOREIGN KEY (SERIAL_V) REFERENCES VENTA;
ALTER TABLE VENTA_N
	ADD CONSTRAINT FK_VENTA_N_ARTICULO_N FOREIGN KEY (NUM_INV) REFERENCES ARTICULO_N;
ALTER TABLE VENTA_N
	ADD CONSTRAINT SERIAL_V_VALID_VENTA_N CHECK(SERIAL_V>0);
ALTER TABLE VENTA_N
	ADD CONSTRAINT NUM_INV_VALID_VENTA_N CHECK(NUM_INV>0);
ALTER TABLE VENTA_N
	ADD CONSTRAINT CANTIDAD_VALID_VENTA_N CHECK(CANTIDAD>-1);



ALTER TABLE VENTA_U 
	ADD CONSTRAINT PK_VENTA_U PRIMARY KEY (SERIAL_V, NUM_INV);
ALTER TABLE VENTA_U
	ADD CONSTRAINT FK_VENTA_U_VENTA FOREIGN KEY (SERIAL_V) REFERENCES VENTA;
ALTER TABLE VENTA_U
	ADD CONSTRAINT FK_VENTA_U_ARTICULO_U FOREIGN KEY (NUM_INV) REFERENCES ARTICULO_U;
ALTER TABLE VENTA_U
	ADD CONSTRAINT SERIAL_V_VALID_VENTA_U CHECK(SERIAL_V>0);
ALTER TABLE VENTA_U
	ADD CONSTRAINT NUM_INV_VALID_VENTA_U CHECK(NUM_INV>0);
ALTER TABLE VENTA_U
	ADD CONSTRAINT CANTIDAD_VALID_VENTA_U CHECK(CANTIDAD>-1);


ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT PK_REALIZA_VENTA PRIMARY KEY	(SERIAL_F,CEDULA_CLIENTE,CEDULA_VENDEDOR);
ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT FK_REALIZA_VENTA_VENTA FOREIGN KEY (SERIAL_F) REFERENCES VENTA;
ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT FK_REALIZA_VENTA_VENDEDOR FOREIGN KEY (CEDULA_VENDEDOR) REFERENCES VENDEDOR;
ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT FK_REALIZA_VENTA_CLIENTE FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE;
ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT SERIAL_F_VALID_REALIZA_VENTA CHECK(SERIAL_F>0);
ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT CEDULA_CLIENTE_VALID_REALIZA_VENTA CHECK(CEDULA_CLIENTE>0);
ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT CEDULA_VENDEDOR_VALID_REALIZA_VENTA CHECK(CEDULA_VENDEDOR>0);


ALTER TABLE REALIZA_TRUQUE
	ADD CONSTRAINT PK_REALIZA_TRUEQUE PRIMARY KEY (SERIAL_R,CEDULA_CLIENTE,CEDULA_VENDEDOR);
ALTER TABLE REALIZA_TRUQUE
	ADD CONSTRAINT FK_REALIZA_TRUEQUE_TRUEQUE FOREIGN KEY (SERIAL_R) REFERENCES TRUQUE;
ALTER TABLE REALIZA_TRUQUE
	ADD CONSTRAINT FK_REALIZA_TRUEQUE_VENDEDOR FOREIGN KEY (CEDULA_VENDEDOR) REFERENCES VENDEDOR;
ALTER TABLE
	ADD CONSTRAINT FK_REALIZA_TRUEQUE_CLIENTE FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE;
ALTER TABLE REALIZA_TRUQUE
	ADD CONSTRAINT SERIAL_F_VALID_REALIZA_TRUEQUE CHECK(SERIAL_R>0);
ALTER TABLE REALIZA_TRUQUE
	ADD CONSTRAINT CEDULA_CLIENTE_VALID_REALIZA_TRUEQUE CHECK(CEDULA_CLIENTE>0);
ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT CEDULA_VENDEDOR_VALID_REALIZA_TRUEQUE CHECK(CEDULA_VENDEDOR>0);


ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT PK_REALIZA_PEDIDO PRIMARY KEY (NUM_PEDIDO,CEDULA_CLIENTE,CEDULA_VENDEDOR);
ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT FK_REALIZA_PEDIDO_PEDIDO FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO;
ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT FK_REALIZA_PEDIDO_VENDEDOR FOREIGN KEY (CEDULA_VENDEDOR) REFERENCES VENDEDOR;
ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT FK_REALIZA_PEDIDO_CLIENTE FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE;
ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT SERIAL_F_VALID_REALIZA_PEDIDO CHECK(NUM_PEDIDO>0);
ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT CEDULA_CLIENTE_VALID_REALIZA_PEDIDO CHECK(CEDULA_CLIENTE>0);
ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT CEDULA_VENDEDOR_VALID_REALIZA_PEDIDO CHECK(CEDULA_VENDEDOR>0);