ALTER TABLE MARCA
	ADD CONSTRAINT PK_MARCA PRIMARY KEY (NOMBRE);

ALTER TABLE MODELO 
	ADD CONSTRAINT FK_MODELO FOREIGN KEY (NOMBRE_MARCA) REFERENCES MARCA;

ALTER TABLE PRODUCTO
	ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO);
	ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (NOMBRE_MARCA,NOMBRE_MODELO) REFERENCES MODELO;
	ADD CONSTRAINT NO_NEGATIVIDAD_CODIGO_PRODUCTO CHECK(CODIGO>0);

ALTER TABLE LISTA_PRECIOS
	ADD CONSTRAINT PK_LISTA_PRECIOS PRIMARY KEY (CODIGO_P,AÑO_ELAB);
	ADD CONSTRAINT FK_LISTA_PRECIOS FOREIGN KEY (CODIGO_P) REFERENCES PRODUCTO;
	ADD CONSTRAINT AÑO_LISTA_PRECIOS CHECK(AÑO_ELAB>1900);
	ADD CONSTRAINT NO_NEGATIVIDAD_CODIGO_P_LISTA_PRECIOS CHECK(CODIGO_P>0);
	ADD CONSTRAINT NO_NEGTIVIDAD_PRECIO_LISTA_PRECIOS CHECK(PRECIO>0);

ALTER TABLE PROVEEDORA
	ADD CONSTRAINT PK_PROVEEDORA PRIMARY KEY (RIF);

ALTER TABLE TELEFONO_PRO
	ADD CONSTRAINT PK_TELEFONO_PRO PRIMARY KEY (RIF_P, NUMERO);
	ADD CONSTRAINT FK_TELEFONO_PRO FOREIGN KEY (RIF_P) REFERENCES PROVEEDORA;
	ADD CONSTRAINT NO_NEGATIVIDAD_TLF_TELEFONO_PRO CHECK(TELEFONO>0);

ALTER TABLE ORDEN
	ADD CONSTRAINT PK_ORDEN PRIMARY KEY (NUM);
	ADD CONSTRAINT NO_NEGATIVIDAD_MONTO_ORDEN CHECK(MONTO>0);
	ADD CONSTRAINT NO_NEGATIVIDAD_NUMERO_ORDEN CHECK(NUMERO>0);

ALTER TABLE SE_PIDE
	ADD CONSTRAINT PK_SE_PIDE PRIMARY KEY (CODIGO_P,NUM_ORDEN);
	ADD CONSTRAINT FK_SE_PIDE_PRODCTO FOREIGN KEY (CODIGO_P) REFERENCES PRODUCTO;
	ADD CONSTRAINT FK_SE_PIDE_ORDEN FOREIGN KEY (NUM_ORDEN) REFERENCES ORDEN;
	ADD CONSTRAINT NO_NEGATIVIDAD_CODIGO_P_SE_PIDE CHECK(CODIGO_P>0);
	ADD CONSTRAINT NO_NEGATIVIDAD_NUM_ORDEN_SE_PIDE CHECK(NUM_ORDEN>0);
	ADD CONSTRAINT NO_NEGATIVIDAD_CANTIDAD_SE_PIDE CHECK(CANTIDAD>0);

ALTER TABLE LOTE
	ADD CONSTRAINT PK_LOTE PRIMARY KEY (SERIAL_F);
	ADD CONSTRAINT FK_LOTE_ORDEN FOREIGN KEY (NUM_ORDEN) REFERENCES ORDEN;
	ADD CONSTRAINT FK_LOTE_PROVEEDORA FOREIGN KEY (RIF_P) REFERENCES PROVEEDORA;
	ADD CONSTRAINT NO_NEGATIVIDAD_SERIAL_F_LOTE CHECK(SERIAL_F>0);
	ADD CONSTRAINT NO_NEGATIVIDAD_NUM_ORDEN_LOTE CHECK(NUM_ORDEN>0);
	ADD CONSTRAINT NO_NEGATIVIDAD_MONTO_LOTE CHECK(MONTO>0);

ALTER TABLE SE_PAGA
	ADD CONSTRAINT PK_SE_PAGA PRIMARY KEY (SERIAL_L);
	ADD CONSTRAINT FK_SE_PAGA PRIMARY KEY (SERIAL_L) REFERENCES LOTE;

ALTER TABLE ARTICULO_N
	ADD	CONSTRAINT PK_ARTICULO_N PRIMARY KEY (NUM_INV);
	ADD CONSTRAINT FK_ARTICULO_N FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO;

ALTER TABLE ARTICULO_U
	ADD CONSTRAINT PK_ARTICULO_U PRIMARY KEY (NUM_INV);
	ADD CONSTRAINT FK_ARTICULO_U FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO;

ALTER TABLE CONTIENE
	ADD CONSTRAINT PK_CONTIENE PRIMARY KEY (FACT_LOTE, NUM_INV);
	ADD CONSTRAINT FK_CONTIENE_LOTE FOREIGN KEY (FACT_LOTE) REFERENCES LOTE;
	ADD CONSTRAINT FK_CONTIENE_ARTICULO_N FOREIGN KEY (NUM_INV) REFERENCES ARTICULO_N;

ALTER TABLE PRIMA 
	ADD CONSTRAINT PK_PRIMA PRIMARY KEY (SEXO, GRUPO_ET);

ALTER TABLE DEPENDIENTE
	ADD CONSTRAINT PK_DEPENDIENTE PRIMARY KEY (NUM_DEP);
	ADD	CONSTRAINT FK_DEPENDIENTE FOREIGN KEY (SEXO, GRUPO_ET) REFERENCES PRIMA;

ALTER TABLE PERSONA 
	ADD CONSTRAINT PK_PERSONA PRIMARY KEY (CEDULA);

ALTER TABLE TELEFONO_P
	ADD CONSTRAINT PK_TELEFONO_P PRIMARY KEY (CEDULA,NUMERO);
	ADD CONSTRAINT FK_TELEFONO_P FOREIGN KEY (CEDULA) REFERENCES PERSONA;

ALTER TABLE EMPLEADO
	ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CEDULA);
	ADD CONSTRAINT FK_EMPLEADO FOREIGN KEY (CEDULA) REFERENCES PERSONA;

ALTER TABLE PARIENTE
	ADD CONSTRAINT PK_PARIENTE PRIMARY KEY (NUM_DEP, CEDULA),
	ADD CONSTRAINT FK_PARIENTE_DEPENDIENTE FOREIGN KEY (NUM_DEP) REFERENCES DEPENDIENTE;
	ADD	CONSTRAINT FK_PARIENTE_PERSONA FOREIGN KEY (CEDULA) REFERENCES PERSONA;

ALTER TABLE VENDEDOR 
	ADD CONSTRAINT PK_VENDEDOR PRIMARY KEY (CEDULA);
	ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (CEDULA) REFERENCES EMPLEADO;

ALTER TABLE ADMINISTRATIVO 
	ADD CONSTRAINT PK_ADMINISTRATIVO PRIMARY KEY (CEDULA);
	ADD CONSTRAINT FK_ADMINISTRATIVO FOREIGN KEY (CEDULA) REFERENCES EMPLEADO; 

ALTER TABLE CLIENTE
	ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CEDULA);
	ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (CEDULA) REFERENCES PERSONA;

ALTER TABLE PEDIDO
	ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUM_PEDIDO);

ALTER TABLE SE_SOLICITA
	ADD CONSTRAINT PK_SE_SOLICITA PRIMARY KEY (NUM_PEDIDO, CODIGO_P);

ALTER TABLE TRUEQUE
	ADD CONSTRAINT PK_TRUEQUE PRIMARY KEY (SERIAL_R);

ALTER TABLE CAMBIO 
	ADD CONSTRAINT PK_CAMBIO PRIMARY KEY (NUM_INV_C, SERIAL_TRUQUE);
	ADD CONSTRAINT FK_CAMBIO_ARTICULO_U FOREIGN KEY (NUM_INV_C) REFERENCES TRUEQUE;
	ADD CONSTRAINT FK_CAMBIO_TRUEQUE FOREIGN KEY (SERIAL_TRUQUE) REFERENCES TRUEQUE;

ALTER TABLE VENTA
	ADD CONSTRAINT PK_VENTA PRIMARY KEY (SERIAL_F);

ALTER TABLE VENTA_N
	ADD CONSTRAINT PK_VENTA_N PRIMARY KEY (SERIAL_V, NUM_INV);
	ADD CONSTRAINT FK_VENTA_N_VENTA FOREIGN KEY (SERIAL_V) REFERENCES VENTA;
	ADD CONSTRAINT FK_VENTA_N_ARTICULO_N FOREIGN (NUM_INV) REFERENCES ARTICULO_N;

ALTER TABLE VENTA_U 
	ADD CONSTRAINT PK_VENTA_U PRIMARY KEY (SERIAL_V, NUM_INV);
	ADD CONSTRAINT FK_VENTA_U_VENTA FOREIGN KEY (SERIAL_V) REFERENCES VENTA;
	ADD CONSTRAINT FK_VENTA_U_ARTICULO_U FOREIGN KEY (NUM_INV) REFERENCES ARTICULO_U;

ALTER TABLE REALIZA_VENTA
	ADD CONSTRAINT PK_REALIZA_VENTA PRIMARY KEY	(SERIAL_F,CEDULA_CLIENTE,CEDULA_VENDEDOR);
	ADD CONSTRAINT FK_REALIZA_VENTA_VENTA FOREIGN KEY (SERIAL_F) REFERENCES VENTA;
	ADD CONSTRAINT FK_REALIZA_VENTA_VENDEDOR FOREIGN KEY (CEDULA_VENDEDOR) REFERENCES VENDEDOR;
	ADD CONSTRAINT FK_REALIZA_VENTA_CLIENTE FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE;

ALTER TABLE REALIZA_TRUQUE
	ADD CONSTRAINT PK_REALIZA_TRUEQUE PRIMARY KEY (SERIAL_R,CEDULA_CLIENTE,CEDULA_VENDEDOR);
	ADD CONSTRAINT FK_REALIZA_TRUEQUE_TRUEQUE FOREIGN KEY (SERIAL_R) REFERENCES TRUQUE;
	ADD CONSTRAINT FK_REALIZA_TRUEQUE_VENDEDOR FOREIGN KEY (CEDULA_VENDEDOR) REFERENCES VENDEDOR;
	ADD CONSTRAINT FK_REALIZA_TRUEQUE_CLIENTE FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE;

ALTER TABLE REALIZA_PEDIDO
	ADD CONSTRAINT PK_REALIZA_PEDIDO PRIMARY KEY (NUM_PEDIDO,CEDULA_CLIENTE,CEDULA_VENDEDOR);
	ADD CONSTRAINT FK_REALIZA_PEDIDO_PEDIDO FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO;
	ADD CONSTRAINT FK_REALIZA_PEDIDO_VENDEDOR FOREIGN KEY (CEDULA_VENDEDOR) REFERENCES VENDEDOR;
	ADD CONSTRAINT FK_REALIZA_PEDIDO_CLIENTE FOREIGN KEY (CEDULA_CLIENTE) REFERENCES CLIENTE;
